context:
  name: abb_libegm
  version: 1.0.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  git: https://github.com/ros-industrial/abb_libegm
  rev: 2c9350abfb67131cae796805fed8cd6eeb2ab7f9

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - libprotobuf 3.21.* # main dependency for ABB EGM
    - boost-cpp
  run:
    #nothing because both dependencies have run_export in their recipe, so they will be automatically added to the run requirements
