context:
  name: abb_libegm
  version: 1.0.1 # O la versione della release GitHub

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  git: https://github.com/ros-industrial/abb_libegm
  rev: 2c9350abfb67131cae796805fed8cd6eeb2ab7f9
  # rattler-build scarica ed estrae il codice in automatico

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }} # Usa il compilatore corretto per la piattaforma corrente
    - cmake
    - ninja
  host:
    - libprotobuf 3.21.* # La dipendenza fondamentale per EGM
    - boost
  run:
    - libprotobuf 3.21.*
